### PR TITLE
add docker-compose support

### PR DESCRIPTION
**Pull request by rgl**
This adds support for using docker-compose. You can now just run `docker-compose up` and it will automatically build the `tink-wizard` container image (it builds it from source; so you do not even need go in your machine), it will then launch redis and then the tink-wizard container.

Please note that I had to remove the `.env` file because its not compatible with docker-compose (it complains about white-spaces in `.env`; I think you cannot have `export ` before a variable declaration).

PS: I'm using this at https://github.com/rgl/rpi-tinkerbell-vagrant.

### CODE REVIEW

**Comment by nshalman** [comment]
This looks pretty stale. Can it be closed out or is there still some valuable work here?

**Comment by gauravgahlot** [comment]
@nshalman I have already started work to bring the dashboard back to life and in sync with tink. So, yeah I could use this PR.

**Comment by nshalman** [comment]
I failed to notice that this PR is in the repo that had moved out of the @tinkerbell org during today's triage party.

**Comment by gauravgahlot** [comment]
This won't be required anymore.

**Pull request closed without merging**
